### ISSUE TITLE
consider configuring bash --without-bash-malloc ?

### ISSUE THREAD

**Issue by moshelooks** [conda-forge/bash-feedstock#15]
By default bash defines its own ancient and thread-hostile malloc(), which creates a number of issues (basically any program that tries to link with bash and perform / analyze malloc calls will have a bad time). Fortunately this can be disabled by setting the `--without-bash-malloc` flag when running `./configure`. Many (most?) linux distributions do this when building their bash packages (debian/ubuntu, alpine, void, &c). Would you consider adding this to the conda-forge builds as well? 

I believe this ought to be as simple as adding `--without-bash-malloc` [here](https://github.com/conda-forge/bash-feedstock/blob/4258462650ff5a12bc61fdbc8ffd8879ee55aa57/recipe/build.sh#L7) - happy to send a PR if you'd accept it.

Thank you!

References
* https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1751011
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865599#15
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849517

**Comment by matthiasdiener** [comment]
Thanks @moshelooks - I'd be supportive of compiling with `--without-bash-malloc`.

**Comment by moshelooks** [comment]
Awesome, just sent #16 for review. This is my first conda-forge PR, please let me know if I'm doing anything wrong.
